---
- name: Pull docker image of the Calculator
  hosts: all
  tasks:
    - name: pull docker image
      shell: docker pull abhijain614/miniproject

    - name: running container
      shell: docker run --name miniproject -it -d abhijain614/miniproject /bin/bash
